
import Acer from "../Assets/Laptops/acer.jpg";
import AsusVivoBook from "../Assets/Laptops/asusvivobook.jpg";
import Dell from "../Assets/Laptops/dell.jpg";
import Honor from "../Assets/Laptops/honor.jpg";
import HP15C from "../Assets/Laptops/hp15c.jpg";
import Lenovo from "../Assets/Laptops/lenovo.jpg";
import Macbook from "../Assets/Laptops/macbook.jpg";
import MI from "../Assets/Laptops/mi.jpg";
import Redmi from "../Assets/Laptops/redmi.jpg";

export const LaptopDetails = [
    {
    id:0,
    name:"HP 15C 12th Gen",
    image:<img src={HP15C} height="250px" width="240px" />,
    os:"Pre-Loaded Windows 11 Home, Microsoft Office Home and Student 2021",
    battery:"3-cell , 41Wh Li-Ion , Support Fast Charging",
    ports:"1 SuperSpeed USB Type-C , 2 SuperSpeed USB Type-1 HeadPhone/Microphone Combo",
    processor:"Intel Core i5 - 1240p (upto 4.4GHz speed)",
    storage:"8GB DDR4 RAM 9 (2 x 4GB), 512GB PCle Nvme M.2 SSD",
    dng:"39.9cm (15.6 inch) FHD , Graphics: Intel Iris Xe Graphics",
    mp:"68,465",
    sp:"57,990",
    residual:"Save 10,500 ( 15% off )",
    price:57990,
    },
    {
    id:1,
    name:"Asus VivoBook 15",
    image:<img src={AsusVivoBook} height="250px" width="240px" />,
    os:"Pre-Loaded Windows 11 Home, Microsoft Office Home and Student 2021",
    battery:"3-cell , 41Wh Li-Ion , Support Fast Charging",
    ports:"1 SuperSpeed USB Type-C , 2 SuperSpeed USB Type-1 HeadPhone/Microphone Combo",
    processor:"Intel Core i5 - 1240p (upto 4.4GHz speed)",
    storage:"8GB DDR4 RAM 9 (2 x 4GB), 512GB PCle Nvme M.2 SSD",
    dng:"39.9cm (15.6 inch) FHD , Graphics: Intel Iris Xe Graphics",
    mp:"68,465",
    sp:"57,990",
    residual:"Save 10,500 ( 15% off )",
    price:57990,
    },
    {
    id:2,
    name:"Acer One 14",
    image:<img src={Acer} height="250px" width="240px" />,
    os:"Pre-Loaded Windows 11 Home, Microsoft Office Home and Student 2021",
    battery:"3-cell , 41Wh Li-Ion , Support Fast Charging",
    ports:"1 SuperSpeed USB Type-C , 2 SuperSpeed USB Type-1 HeadPhone/Microphone Combo",
    processor:"Intel Core i5 - 1240p (upto 4.4GHz speed)",
    storage:"8GB DDR4 RAM 9 (2 x 4GB), 512GB PCle Nvme M.2 SSD",
    dng:"39.9cm (15.6 inch) FHD , Graphics: Intel Iris Xe Graphics",
    mp:"68,465",
    sp:"57,990",
    residual:"Save 10,500 ( 15% off )",
    price:57990,
    },
    {
    id:3,
    name:"Lenovo IdeaPad Slim 3",
    image:<img src={Lenovo} height="250px" width="240px" />,
    os:"Pre-Loaded Windows 11 Home, Microsoft Office Home and Student 2021",
    battery:"3-cell , 41Wh Li-Ion , Support Fast Charging",
    ports:"1 SuperSpeed USB Type-C , 2 SuperSpeed USB Type-1 HeadPhone/Microphone Combo",
    processor:"Intel Core i5 - 1240p (upto 4.4GHz speed)",
    storage:"8GB DDR4 RAM 9 (2 x 4GB), 512GB PCle Nvme M.2 SSD",
    dng:"39.9cm (15.6 inch) FHD , Graphics: Intel Iris Xe Graphics",
    mp:"68,465",
    sp:"57,990",
    residual:"Save 10,500 ( 15% off )",
    price:57990,
    },
    {
    id:4,
    name:"Dell Inspiron 3515 Laptop",
    image:<img src={Dell} height="250px" width="240px" />,
    os:"Pre-Loaded Windows 11 Home, Microsoft Office Home and Student 2021",
    battery:"3-cell , 41Wh Li-Ion , Support Fast Charging",
    ports:"1 SuperSpeed USB Type-C , 2 SuperSpeed USB Type-1 HeadPhone/Microphone Combo",
    processor:"Intel Core i5 - 1240p (upto 4.4GHz speed)",
    storage:"8GB DDR4 RAM 9 (2 x 4GB), 512GB PCle Nvme M.2 SSD",
    dng:"39.9cm (15.6 inch) FHD , Graphics: Intel Iris Xe Graphics",
    mp:"68,465",
    sp:"57,990",
    residual:"Save 10,500 ( 15% off )",
    price:57990,
    },
    {
    id:5,
    name:"Mi NoteBook Pro",
    image:<img src={MI} height="250px" width="240px" />,
    os:"Pre-Loaded Windows 11 Home, Microsoft Office Home and Student 2021",
    battery:"3-cell , 41Wh Li-Ion , Support Fast Charging",
    ports:"1 SuperSpeed USB Type-C , 2 SuperSpeed USB Type-1 HeadPhone/Microphone Combo",
    processor:"Intel Core i5 - 1240p (upto 4.4GHz speed)",
    storage:"8GB DDR4 RAM 9 (2 x 4GB), 512GB PCle Nvme M.2 SSD",
    dng:"39.9cm (15.6 inch) FHD , Graphics: Intel Iris Xe Graphics",
    mp:"68,465",
    sp:"57,990",
    residual:"Save 10,500 ( 15% off )",
    price:57990,
    },
    {
    id:6,
    name:"Redmi Book 15 Pro",
    image:<img src={Redmi} height="250px" width="240px" />,
    os:"Pre-Loaded Windows 11 Home, Microsoft Office Home and Student 2021",
    battery:"3-cell , 41Wh Li-Ion , Support Fast Charging",
    ports:"1 SuperSpeed USB Type-C , 2 SuperSpeed USB Type-1 HeadPhone/Microphone Combo",
    processor:"Intel Core i5 - 1240p (upto 4.4GHz speed)",
    storage:"8GB DDR4 RAM 9 (2 x 4GB), 512GB PCle Nvme M.2 SSD",
    dng:"39.9cm (15.6 inch) FHD , Graphics: Intel Iris Xe Graphics",
    mp:"68,465",
    sp:"57,990",
    residual:"Save 10,500 ( 15% off )",
    price:57990,
    },
    {
    id:7,
    name:"Honor MagicBook X14",
    image:<img src={Honor} height="250px" width="240px" />,
    os:"Pre-Loaded Windows 11 Home, Microsoft Office Home and Student 2021",
    battery:"3-cell , 41Wh Li-Ion , Support Fast Charging",
    ports:"1 SuperSpeed USB Type-C , 2 SuperSpeed USB Type-1 HeadPhone/Microphone Combo",
    processor:"Intel Core i5 - 1240p (upto 4.4GHz speed)",
    storage:"8GB DDR4 RAM 9 (2 x 4GB), 512GB PCle Nvme M.2 SSD",
    dng:"39.9cm (15.6 inch) FHD , Graphics: Intel Iris Xe Graphics",
    mp:"68,465",
    sp:"57,990",
    residual:"Save 10,500 ( 15% off )",
    price:57990,
    },
    {
    id:8,
    name:"Apple MacBook Air",
    image:<img src={Macbook} height="250px" width="240px" />,
    os:"Pre-Loaded Windows 11 Home, Microsoft Office Home and Student 2021",
    battery:"3-cell , 41Wh Li-Ion , Support Fast Charging",
    ports:"1 SuperSpeed USB Type-C , 2 SuperSpeed USB Type-1 HeadPhone/Microphone Combo",
    processor:"Intel Core i5 - 1240p (upto 4.4GHz speed)",
    storage:"8GB DDR4 RAM 9 (2 x 4GB), 512GB PCle Nvme M.2 SSD",
    dng:"39.9cm (15.6 inch) FHD , Graphics: Intel Iris Xe Graphics",
    mp:"68,465",
    sp:"57,990",
    residual:"Save 10,500 ( 15% off )",
    price:57990,
    },
    
]